### ISSUE TITLE
Property saved as false becomes NULL

### ISSUE THREAD

**Issue by noughts** [parse-community/parse-php-sdk#102]
We've found a somewhat mysterious behaviour.
Although the bool-type column of a fetched object is set to false, it returns as null.
We are using the PHP SDK ver.1.1.2, PHP is 5.6.5.

Test Code:

``` php
// Saves a Test Object
$uuid = uniqid();
$obj = new ParseObject("TestObject");
$obj->set("uuid", $uuid);
$obj->set("someProp", false);
$obj->save();

// Query the saved Object
$query = new ParseQuery("TestObject");
$query->equalTo("uuid", $uuid);
$result = $query->first();

echo $result->has("someProp");
echo $result->get("someProp");
```

Expected output:

```
true
false
```

Actual output:

```
false
NULL
```

By the way, when changing line 5 `$obj->set("someProp", false);` to `$obj->set("someProp", true);`
it returns:

```
true
true
```

and this is expected.

A similar code with Javascript SDK returns an expected result.
How can we have the same result in PHP SDK?

Thanks in advance for your advice.

**Comment by gfosco** [comment]
I'll try to take a look at this next week.

**Comment by noughts** [comment]
Any updates?

**Comment by facebook-github-bot-4** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by yaman-jain** [comment]
Hey @noughts ,

May be you should try this.

echo $result->has("someProp") === true ? 'true' : 'false';
echo $result->get("someProp") === true ? 'true' : 'false';

Because those are boolean variables, even echo statement will not render them as you have mentioned.
For eg. you can try this...
echo true;
echo false;

PS: I'm using php 5.6.7

**Comment by montymxb** [comment]
This issue appears to have been resolved but a commit since it's original opening. Running the test code provided above against the latest sdk provides the expected results now. If there's still a problem regarding this we can always open it up, but since it looks resolved I'll go ahead and close this!
