### ISSUE TITLE
Same Issue as #157: Unknown SSL protocol error in connection to api.parse.com:443

### ISSUE THREAD

**Issue by ghost** [parse-community/parse-php-sdk#184]
This issue seems to be popping up a lot - we see it about once daily on our production site which obviously isn't good. Issue #157 was closed for some reason without a resolution

```
 curl_setopt($rest, CURLOPT_SSL_VERIFYPEER, false); 
```

That would work but is a security risk so it obviously a no go. 
My site is served over SSL and I've had no problems on that front, I believe the error relates to the site you are trying to connect to? 

http://stackoverflow.com/a/16495053/4007992 seems to look quite promising and straightforward. Can we get some advice on the recommended way to deal this error? 

I'm not really seeing this as a bug per se, but its affecting people's production instances so we should really try and get some sort of advice or best practice out there

**Comment by montymxb** [comment]
Is anyone still having this issue?

 I have not personally seen this but it would appear to be less about this SDK and more regarding the local installation and setup. If for some reason curl isn't finding/using the appropriate Certificate Authority (CA) cert for your server you can try to indicate the directory to search for the specific CA cert needed via
```php
curl_setopt($ch, CURLOPT_CAPATH, "/path/to/your/cacert/dir/")
```
or (as the SO post points out for Windows) you can clarify an alternate cert to verify against via
```php
curl_setopt ($ch, CURLOPT_CAINFO, "/path/to/your/cacert.pem");
```

This <i>should</i> ensure you are using the correct CA to verify against.

 However I am not sure how intermittent issues will fare against this. I would either put together some serious logging or start doing some in depth tests to isolate any variance between 'good' and 'bad' cases. Not exactly a solution but it get you somewhere if anyone is still dealing with this issue.

**Comment by montymxb** [comment]
Going to go ahead and close this up now that **api.parse.com** is down and the SSL certificate is no longer valid. Since this is have come up significant changes have been made to how this sdk can connect to a server via the use of one or more http clients, each with the ability to point to an up to date CA file as well.

If anyone is still having issues or concerns regarding these please add your comments here and we'll reopen the issue. It would be especially helpful if issues could come with a mention of the local setup and the domain that the issue is resulting from.

**Comment by kiennatibula** [comment]
Hi, I am having this issue also I use the php SDK in back4app => Unknown SSL protocol error in connection to parseapi.back4app.com:443
