### ISSUE TITLE
ParseObject::delete($key) doesn't remove data

### ISSUE THREAD

**Issue by jorvikapps** [parse-community/parse-php-sdk#257]
I'm trying to remove a single key-value from a ParseObject. If I try 

```
$events = getAllEventsWithBroadcastId($id);
if($events) {
    for($index=0; $index<count($events); $index++) {
        $event = $events[$index];
        $event->set("isActive", True);
        $event->set("wasDeleted", False);
        $event->delete("endDate");
    }

    print("<pre>");
    print_r($event);
    print("</pre>");

    ParseObject::saveAll($events, True);

    $retVal = array('success'=>True);
} else {
    $retVal = array('success'=>False, 'error'=>'Failed to restart event');
}
```

This doesn't work - endDate still has it's original value.

If I call `$event->clear()` this does clear the field (along with all the others).

I'm confused as the call to clear is just looping through available keys, and calling `delete($key)`. Any help would be hugely appreciated.

**Comment by montymxb** [comment]
@jorvikapps The ```delete``` call _should_ work just as well on it's own as the ```clear``` call would for all possible key. I would initially wonder if you had an issue where you were updating a variable within the [scope of a for loop](http://stackoverflow.com/questions/16456875/updating-an-item-in-array), however you mentioned a call to ```clear``` works (I'm assuming in the same for loop), which mostly removes that as an option.

With that in mind I'm not too sure as to what would be missing. It doesn't appear to be an sdk bug, but I would carefully go back and verify that after deleting your value the object is directly affected. 

If you can verify this, and the next step is ```ParseObject::saveAll``` than you _may_ be updating a value in scope rather than by reference. If that's the case you can try setting back your updated ```$event``` back to ```$events[$index]``` after the changes have been made, just a thought.

**Comment by montymxb** [comment]
Closing as outdated with lack of followup. This appears to have been resolved in the latest releases as well.
