### ISSUE TITLE
Request URL too large 414 error in containedIn query

### ISSUE THREAD

**Issue by ankitkcueblocks** [parse-community/parse-php-sdk#264]
Request URL too large 414 error in containedIn query

**Comment by montymxb** [comment]
This is a bit old, but can you provide further details as to what caused this? Particularly the URL that is giving you a 414.

**Comment by montymxb** [comment]
I took a look at this recently, and given the current setup with parse-server I was able to trigger a _similar_ error by submitting a singular request with excessive query parameters. Exceeding a given url size will cause parse-server to spit out something like `Empty reply from server` with a curl code of `52`, which corresponds to `CURLE_GOT_NOTHING`.

The error is correct, but is a _bit_ vague. I'm considering putting in a check to view for error code `52`, and provide the default exception with an extra line or two for insight into this.

**Comment by montymxb** [comment]
So, readdressing this, I dug into this a bit and have decided not to modify the sdk for special behavior in this regard. It's not that it wouldn't be useful, it's that it may not be _entirely_ accurate in some cases. 

For example, when utilzing the `curl` client a code **52** is returned with the 'empty server' reply mentioned above. However the same request utilized via the `stream` client returns something like:
```
...failed to open stream: HTTP request failed!
```
with a code of **2**. Pinning the reporting functionality on the code along (or the message) along with factoring in the size of the url requested with is not necessarily going to definitively indicate that a url was too large.

To wrap this up, the original observation that a code `414` was a specific message is actual the ideal response. It clearly indicates the cause is a GET request exceeding a size limitation. However this, being an HTTP error code, is returned in response to an HTTP request, and is thus something that the server decides on. The sdk may only interpret what is then returned. In the best case scenario the code/message originally reported here is what you have returned, rather than just `52` and `Empty reply...` . Again, this is up to the server.
