### ISSUE TITLE
Is someone willing to fully explain using Parse on a website to me?

### ISSUE THREAD

**Issue by nFToxiic** [parse-community/parse-php-sdk#281]
Hello,

I've been looking around which program to use for setting up a messaging system on my website. So I came across Parse which looks promising. But I dont really know how to combine my website with the code parse provides in the guide.

It would be amazing if someone is willing to push me into the right direction.
Assistance via skype would be even better ^^
Skype: pallaman4

Kind regards,

Youri v.d. Heuvel

**Comment by montymxb** [comment]
Well for starters you're going to need to get a running instance of [Parse Server](https://github.com/ParsePlatform/parse-server) going. The home page in the link for the project has some really good examples that you can follow to get up and running (and to verify everything works).

For a local setup of parse-server you can get a test instance going in about 3 lines (from the front page of the parse-server project):
```shell
$ npm install -g parse-server mongodb-runner
$ mongodb-runner start
$ parse-server --appId MyAppId --masterKey MyMasterKey --databaseURI mongodb://localhost/test
```

For setting an actual production instance I would recommend you set it up as an [express website](https://github.com/ParsePlatform/parse-server#user-content-parse-server--express).

As for the sdks you can pick and choose which one you'd like. The home page for the php sdk here has some fairly good examples for getting started. A simple php page with parse setup and running might look at a bit like this:
```php

// using composer
require 'vendor/autoload.php';

// or if you cloned this project use the line below instead
//require 'autoload.php';

// initialize parse with your appId, restKey and masterKey
// Parse server does not actually require a restKey, so you can pass null safely instead if you wish
ParseClient::initialize('MyAppId', 'MyRestKey', 'MyMasterKey');

// Point the sdk to your parse server
// first part is the protocol and domain, second is the mount path
// ex. https://my-parse-server.com/parse would like like this below
// default mount is 'parse', unless you've changed it
ParseClient::setServerURL('https://my-parse-server.com','parse');

// Create and save object
$obj = new ParseObject('TestClass');
$obj->set('usingParse', true);
$obj->save();

// Query for the first object in this class, the one that you just saved
$query = new ParseQuery('TestClass');
$foundObject = $query->first();

//  delete this object
$foundObject->destroy();
``` 
If you really want to dig in I would advise reading through the [getting started](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#getting-started) page for parse server (note that the ```ParseClient::setServerURL``` is out of date). For the php sdk you should familiarize yourself with [php sdk guide](http://parseplatform.github.io/docs/php/guide/), although it was written for ParseServer when it was running at Parse.com it's still fairly spot on.

When in doubt you can flip through some of the actual source, checkout here to see if new features are present or go through the issues. 

Everything you need to get going should be up here. Best of luck 👍 .

**Comment by nFToxiic** [comment]
@montymxb My parse server worked correctly since I executed the http://parse.mydomain.com:1337/test.
And everything seemed to be working correctly. But once I try to run my code I get a HTTP 500 error. I must've missed something but I cant figure out what exactly. Are they any common problems with parse that cause that error?

**Comment by montymxb** [comment]
@nFToxiic When in doubt check your logs. Parse server will log to the console or to a file depending on how you set it up, and will most likely have further information on this. Additionally your webserver (probably apache or nginx?) may include some juicy details in their regular and error logs, potentially elaborating on your error. Make sure you're reading all of these thoroughly. With that being said, your client code looks good. 

By the way, when you want to add code, like this:
```php
$code = "php";
```
You can write something like this:
\`\`\`php
$code = "php";
\`\`\`
You can find more about markdown [here](https://guides.github.com/features/mastering-markdown/), it can definitely make your posts easier to go through, especially with syntax highlighting.

In your scenario, given the error code, there's nothing that immediately comes to mind as to why your code would not be working. For me personally I would go through a checklist, checking one variable at a time. Going off the assumption that parse server is already running and reachable.

1. Is mongodb running?
2. Is parse connected to mongodb (logs will help you verify this, for parse-server this is either in the console or logged out to a file in the same directory)
3. Does the appId match.
4. Does the masterKey match.
5. Can I [reach it with curl](https://github.com/ParsePlatform/parse-server#user-content-saving-your-first-object)

Assuming you get to the point and _can_ reach it with curl then you can rest assured it's not the server. From there it's probably something regarding your client side setup, possibly even relating to your php installation. 

Again, and I can't stress this enough, make sure you are reading your logs to try and diagnose issues, this is invaluable to debugging your setup. Otherwise you're kind of flying blind. One of my personal favorites is to 'tail' a log, or to just read the last X lines added and to show new changes as they are written in real time.
```shell
# read the last 100 lines and continue to read as the file is updated
tail -n 100 -f error.log
```

**Comment by montymxb** [comment]
@nFToxiic I'm not sure if anyone here is going to have enough time to walk you through this. I would highly recommend you check the docs listed on [parse's site](https://parseplatform.github.io/) to get started. Best of luck!

**Comment by montymxb** [comment]
It's been some time since this has been opened. I'm going to close this, if you still need help you can always check out the docs above. They should be detailed enough to get you going. Additionally if you have questions be sure to check out [stackoverflow](https://stackoverflow.com/), there's often some good bits there.
