### ISSUE TITLE
Integrating parse php sdk into symfony2 project

### ISSUE THREAD

**Issue by yassine-1995** [parse-community/parse-php-sdk#301]
Hi, I have a problem with integrating parse php sdk into symfony2 project It doesn't work, is it possible at least to integrate it or do i just have to give up ?

**Comment by montymxb** [comment]
@yassine-1995 I'm not too familiar with symfony, perhaps if you could detail how you are trying to integrate this we could help you out a bit? 

I would imagine it should be workable, however you'll have to provide info into the issues you're having, we can't help much otherwise. Any relevant errors would be a start.

**Comment by montymxb** [comment]
Closing this out as there were never any details provided. For integrating the sdk you can either utilize composer or directly require the `autoload.php` as detailed in the [installation section of the README](https://github.com/parse-community/parse-php-sdk#installation). As far as that goes, following either of those steps should result in a working integration on it's own.

@yassine-1995 if you still haven't resolved this and have further details go ahead and put them up here. We're always around to help whenever you have a moment.

**Comment by montymxb** [comment]
Just to ensure that if anyone else every has this problem I went ahead and set up an example symfony project. 

The setup is relatively straight forward following their [instructions](https://symfony.com/doc/current/setup.html). As for incorporating the **parse-php-sdk** we recommend you use the [composer method](https://symfony.com/doc/current/setup.html#creating-symfony-applications-with-composer) to set it up. Using composer allows you to add the following to your **composer.json** under the **require** property:
```json
"parse-php-sdk" : "1.2.*"
```
Be sure to run `composer update` after making this change so you actually have the sdk.

Additionally if you've utilized composer to install symfony then you'll automatically have access to the parse-php-sdk too, given that the vendor folder's contents are autoloaded for you.

Finally you can use the [first page](https://symfony.com/doc/current/page_creation.html) example as a basis for testing out the sdk. Since you're already autoloaded you can add the relevant uses at the top.
```php
use Parse\ParseClient;
use Parse\ParseUser;
```
Initializing the sdk and signing up a new user (or getting the username of the current one) can done by dumping the following right into the `numberAction` method directly:
```php
ParseClient::initialize(
	'app-id-here',
	null,
	'master-key-here'
);
ParseClient::setServerURL('http://localhost:1337', 'parse');

$currentUser = ParseUser::getCurrentUser();

if(!isset($currentUser)) {
	// signup a new user & log them in...

} else {
	// indicate a user is already present...

}
```
At this point all you would need to do is make sure you read through our [php docs](http://docs.parseplatform.org/php/guide/) to familiarize yourself with how to use the sdk. Keep in mind this is a _crude_ example, but it does demonstrate how to get started with symfony.

Note I checked this on symfony3, but you should be just fine working on symfony 2 (or 4). If you're _not_ using **composer** and are cloning this repo directly be sure to require our own autoloader like so to get started.
```php
require "parse-php-sdk/autoload.php";
```
