### ISSUE TITLE
Publish new tag?

### ISSUE THREAD

**Issue by acinader** [parse-community/parse-php-sdk#312]
@montymxb after merging #311 I contemplated cutting a new tag so users could get the new fix.

I ran the unit tests using your parse-server-test repo.

I got four failures so I didn't cut the new tag.  I don't have time to look into the failures now, but creating this issue in case you know anything about them before I look into?:

```
There were 4 failures:

1) Parse\Test\ParseClientTest::testBadApiResponse
Failed asserting that exception of type "Error" matches expected exception "Parse\ParseException".

2) Parse\Test\ParseQueryTest::testOrderByUpdatedAtDesc
Did not return the correct object.
Failed asserting that 2 matches expected 3.

/Users/arthur/code/parse-php-sdk/tests/Parse/ParseQueryTest.php:1569

3) Parse\Test\ParseUserTest::testLoginWithTwitter
Failed asserting that exception message 'Twitter auth configuration missing' contains 'Twitter auth is invalid for this user.'.

4) Parse\Test\ParseUserTest::testLinkWithTwitter
Failed asserting that exception message 'Twitter auth configuration missing' contains 'Twitter auth is invalid for this user.'.

FAILURES!
Tests: 463, Assertions: 1233, Failures: 4.
```

**Comment by montymxb** [comment]
@acinader I took a look and all the tests are passing on my end. However I think I can glean some things from what you've posted.

It looks like the **first** failure could be something to do with the version of [phpunit](https://phpunit.de/) that is running. Using composer it's on version 4, but I _do_ have a local setup that runs version 5. It's quite possible that the mocking feature I introduced is not available in the 4 line, I'll take a look at that. We can always up the version in composer.json.

The **second** failure is something I've seen before. It's intermittent and appears to be timing based. It's an old test from when parse.com was the defacto server that was retained when I updated the test suite for the open source parse variant. I was actually going to look into that sometime tomorrow since it pops up for me periodically. However if you want to check, running it again will sometimes pass, and sometimes fail, ideally it mostly passes; that needs to be resolved... I'll add a PR for that sometime this weekend.

The **third** and **fourth** failures look related to the parse-server-test repo missing twitter configuration in 'auth'. In the most recent version that should be good, you can pull and verify this yourself though in case you've found something else.

Once we address all these we can get that tag up! I'll keep you posted about progress regarding the first & second issues.

**Comment by acinader** [comment]
@montymxb it worked!  nice.  

you want to publish a new tag?

would be super nice to get parse-server-test worked in as a deve dependency in this repo....

**Comment by montymxb** [comment]
@acinader excellent! Glad to hear those fixes worked out. I'll go ahead and push up a new tag real quick here. Although first I think I'm going to up the version # again internally to keep it in track with the current release.

As for the test server I can get that setup on the packagist. From there we can get it added as a dev dependency fairly easily. I can't get to it right at this moment, but I'll make a note to take care of that this upcoming weekend.

**Comment by montymxb** [comment]
Release [1.2.8](https://github.com/parse-community/parse-php-sdk/releases/tag/1.2.8) is now up with the internal version # bumped as well.
