### ISSUE TITLE
SSL certificate error - certificate invalid or non-existent, [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure

### ISSUE THREAD

**Issue by mauriciord** [parse-community/parse-php-sdk#315]
Hello, I'm using a local setup as Google App Engine before Deploy.
But this error appears:
```
Type: Parse\ParseException
Code: 2
Message: file_get_contents(https://thoc.com.br/parse/classes/Loteamento?where=%7B%22deletado%22%3A%7B%22%24ne%22%3Atrue%7D%7D&amp;keys=cidade%2Cbairro%2Cestado%2Clogo%2Cslug%2Cnome%2Ctipo%2Cestagio&amp;order=-estagio): failed to open stream: SSL certificate error - certificate invalid or non-existent, [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)
File: /Users/mauricio/workspace/newsite-thcm/vendor/parse/php-sdk/src/Parse/ParseClient.php
Line: 487
```

I tried to put the *.pem file at project folder e tried with this:
```php
ParseClient::setCAFile(__DIR__ . '/parse-thcm.pem');
```

What am i doing wrong ?

**Comment by mauriciord** [comment]
@montymxb Can you help me ?

**Comment by montymxb** [comment]
Hmmm, it looks like you're using the stream client, did you try out the curl client to begin with or is it not available on your setup? The stream client was recently added, while the curl client has been available since the beginning. If you can give that a run and it works that might help narrow down something in particular regarding the stream client.

Other than that I took a look at the server using [SSL Labs](https://www.ssllabs.com/ssltest/analyze.html?d=thoc.com.br&hideResults=on) to see how everything was setup (you go an A by the way 👍 ). Looks like you guys do support all of the tested TLS protocols: 1.0, 1.1, 1.2. Although I would recommend you drop TLS 1.0, it's already been dropped for [PCI Compliance](https://blog.varonis.com/ssl-and-tls-1-0-no-longer-acceptable-for-pci-compliance/) due to security concerns.

Let me know if you do have the option of utilizing the curl client. If you can and there are issues as well it helps isolate the cause a bit further.

**Comment by mauriciord** [comment]
My SDK is in the latest version. How can i use the curl ?

**Comment by mauriciord** [comment]
Changed to curl client as you said, but:
```php
use Parse\HttpClients\ParseCurlHttpClient as ParseCurlHttpClient;

// ...
try{
  ParseClient::initialize($app_id,null,$master_key);
  ParseClient::setServerURL('https://thoc.com.br','parse');
  ParseClient::setHttpClient(new ParseCurlHttpClient());
  ParseClient::setCAFile(getcwd() . '/server-php.pem');
}
catch (Parse\ParseException $ex){
  echo "Error while sending query.<br>";
  echo "Error code ".$ex->getCode().": ".$ex->getMessage()."<br>";
}
``` 

gives me this error:
```
Fatal error: Call to undefined function Parse\HttpClients\curl_init() in /Users/mauricio/workspace/newsite-thcm/vendor/parse/php-sdk/src/Parse/HttpClients/ParseCurl.php on line 31
```

**Comment by montymxb** [comment]
Oh I see...well curl is the default client when the following code evaluates to true.
```php
return function_exists('curl_init') ? new ParseCurlHttpClient() : new ParseStreamHttpClient();
```
I figured you had explicitly setup the curl client. In your case it appears that curl may _not be available_. If you want to be absolutely sure you can follow the example in the readme to [change the http client](https://github.com/parse-community/parse-php-sdk/blob/master/README.md#user-content-http-clients) to curl explicitly, although you will most likely find that curl is not setup. In addition you should verify that `allow_url_fopen` is enabled in your .ini.

If you think curl is available on your hosting, but for some reason you're not able to get it, you might want to talk to your support for your hosting to verify if curl is in fact available or not.
