### ISSUE TITLE
json_encode shows empty objects

### ISSUE THREAD

**Issue by mauriciord** [parse-community/parse-php-sdk#319]
Hi, i need to pass a Query result as JSON, but my return is that:
```
[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]
```
My code:
```php
$lotQuery = new ParseQuery("Loteamento");
$lotQuery->notEqualTo("deletado", True);
$lotQuery->descending("estagio");
$lotQuery->select(["cidade", "bairro", "estado", "logo", "slug", "nome", "tipo", "estagio"]);
$lotResults = $lotQuery->find();

// this is something like json_encode($lotResults), but with Headers set
$newResponse = $response->withJson($lotResults, 201);

return $newResponse;
```

Why ?

**Comment by montymxb** [comment]
@mauriciord json_encode will request the properties of an object and iterate over those to create a result. However the properties returned are those that are publicly visible, and all the properties in `ParseObject` are either **private** or **protected**; resulting in an array of empty objects!

Instead of running json_encode on the entire array of ParseObjects you can iterate over each one and call `$obj->_encode()` to do the equivalent. That should give you what you're looking for.

**Comment by mauriciord** [comment]
@montymxb Thank you, but my JSON is with backslash, it's just for security or there a way to remove them ?

**Comment by montymxb** [comment]
You can run `json_decode` to decode that JSON before use. Any characters escaped by `json_encode` will be returned as they were during the decoding process.

**Comment by montymxb** [comment]
@mauriciord did you manage to figure this one out?

**Comment by mauriciord** [comment]
Thank you @montymxb
