### ISSUE TITLE
parse as json (ParseQuery)

### ISSUE THREAD

**Issue by mrhaxic** [parse-community/parse-php-sdk#322]
Hi,

how could I parse response/results as json

```
$query = new ParseQuery("Friends");
$results = $query->find();
return $results.toJSON();
```

it is not working.

**Comment by acinader** [comment]
Your issue is that `$results` is an array.  `toJSON()` is method on the object in that array.

Ideally this repo's issues are for issues with the parse php sdk.

If you want more help with how to translate the result into another format, please use StackOverflow with the parse-server and parse-php-sdk tags.
