### ISSUE TITLE
Could not access property of parseObject in js?

### ISSUE THREAD

**Issue by sonysm** [parse-community/parse-php-sdk#354]
I am a new web developer
I receive parse object in views Laravel I can get value of parse object in html Ex {{gamescore->getObjectId()}} 
and I past this object to js I could not access it's property 
any solution?

**Comment by montymxb** [comment]
The JS and PHP sdks run in two completely different environments, they do not interoperate. You can assume that in order to interact with an object in another sdk you will have to create or query for it first as you normally would. 

Please refer to the [JS sdk guide](http://docs.parseplatform.org/js/guide/) for how to handle anything on that end.

**Comment by dplewis** [comment]
@sonysm going between php and js requires encoding and decoding the objects. 

If you have a AJAX call to PHP

PHP
```
$query = new ParseQuery("TestObject");
$object = $query->first();
return json_decode($object->_encode(), true);
```

In JS you access like you would a JSON object.
