### ISSUE TITLE
getAllKeys method of ParseObject doesn't return key for field with null value

### ISSUE THREAD

**Issue by MoonLoq** [parse-community/parse-php-sdk#359]
Why method getAllKeys doesn't return keys for fields with null value?
Can add optional parameter for method 'NotNullOnly' with default value 'True'?
Because i want link ParseObject class with Model in MVC project, and set all fields automatically in loop (sure except objectId, createdAt, updatedAt).

**Comment by montymxb** [comment]
Setting a value to `null` is inferred as an **unset** operation, as can be seen [here](https://github.com/parse-community/parse-php-sdk/blob/master/src/Parse/ParseObject.php#L416) where a set operation is actually applied to the object's estimatedData. Because you are unsetting that value from estimatedData it is no longer present when you request that _specific_ object's keys. 

If you're trying to get all _possible_ keys for a given class, rather than just what's present on an object, I would recommend using **ParseSchema**.
```php
$schema = new ParseSchema('YourClass');
$result = $getSchema->get();
// iterate over fields
foreach($result['fields'] as $fieldName => $fieldData) {
    ...
}
```
This way you can reliably account for all possible keys on an object, whether or not they are actually set per object.
