### ISSUE TITLE
Unable to retrieve/read users emails.

### ISSUE THREAD

**Issue by Shady-AbouElmakarem** [parse-community/parse-php-sdk#385]
### Issue Description

When I try to retrieve users data from the "User" table, I don't get any email within the retrieved users objects, the only email that is retrieved is the current user email.
I also checked the ACL  and public has read access. 

### Steps to reproduce

1- I initiate a simple parse query on the "_User" class or I initiate a simple parse user query.
2- Call the find() function and store the output in a variable called "$results".
3- loop on "$results" and use the encode() function on each result, then push it to an array called "$members", then I send it with the response to the client side.
4- on the client side I retrieve all the data excluding the email key and value.

### Environment Details

- Your PHP Version: 7.0.10
- Your Parse PHP SDK Version: 1.3
- Your Operating System: Windows 10
- VM (only if you're running something like HHVM): **PHP**

### Logs/Traces

none.

**Comment by montymxb** [comment]
This is a feature in parse server [2.3.0](https://github.com/parse-community/parse-server/blob/master/CHANGELOG.md#230) that was added due to concerns of anyone requesting any users and getting their emails. It is considered an unsafe leaking of PII and is removed from results.

If I am correct you can use the **masterKey** in your query request to include the omitted **email** field from user queries.

**Comment by Shady-AbouElmakarem** [comment]
Thanks @montymxb , I can now get the users E-mails, I had to use the masterKey in the find() query just as you said.
