### ISSUE TITLE
Error using greaterThanRelativeTime

### ISSUE THREAD

**Issue by anthonywebster** [parse-community/parse-php-sdk#402]
### Issue Description

~~ I am using the greaterThanRelativeTime method and I have the following error~~

### Steps to reproduce

~~ Please provide the necessary steps here to reproduce this when possible ~~
![image](https://user-images.githubusercontent.com/3496319/42856413-6a8df41a-8a02-11e8-8b30-bc62f0cbca28.png)
### Environment Details

- Your PHP Version: **[5.6]**
- Your Parse PHP SDK Version: **[1.4.*]**
- Your Operating System: **ubuntu**
- VM (only if you're running something like HHVM): **PHP**

### Logs/Traces

~~ Include any relevant logs/traces here ~~
![image](https://user-images.githubusercontent.com/3496319/42856441-8feeef7a-8a02-11e8-97cc-3406964e9d60.png)

**Comment by montymxb** [comment]
Hmm, that's a bit odd. Taking a look server side shows something that hints at [invalid JSON](https://github.com/parse-community/parse-server/search?q=bad+atom&unscoped_q=bad+atom), which is a bit peculiar because this code _seems_ ok from here. I'll have to check the tests later today and verify something hasn't changed.

**Comment by acinader** [comment]
I'm gonna close this as stale.  I am using relative time without issue and no one has me tooed this in years.
